### ISSUE TITLE
'Error downloading feed' message when updating GTFS Feed

### ISSUE THREAD

**Issue by holzmandee** [trilliumtransit/transit-custom-posts#21]
In Transit Custom Posts 'GTFS Settings', when trying to specify a GTFS Feed URL (something like 'http://oregon-gtfs.com/gtfs_data/hoodriver-or-us/hoodriver-or-us.zip'), to update routes, alerts, etc., a error status 104 is returned, specifically: 'Error downloading feed. Please set GTFS feed correctly in GTFS settings first.'

I've narrowed down the cause of the error in the tcp_download_feed() function in gtfs-update.php.  This function is returning null because on line 122:

```
if ( !( $feed_download = @file_get_contents($gtfs_feed, true) ) ) {
		return null;
	}
```

returns null for $feed_download

In this case, `$gtfs_feed` = "http://oregon-gtfs.com/gtfs_data/hoodriver-or-us/hoodriver-or-us.zip"

For some reason this happens on every GTFS feed file that I try to use for the update.

and `@file_get_contents($gtfs_feed)` is returning null.

**Comment by holzmandee** [comment]
Please disregard, a server issue was causing this issue - thank you so much for this plugin

**Comment by philam** [comment]
@holzmandee I'm experiencing the same issue that you did - would you mind posting what your server issue was and the steps that you took to fix it? Thanks
