### ISSUE TITLE
Only one route created on GTFS import

### ISSUE THREAD

**Issue by dudebrains01** [trilliumtransit/transit-custom-posts#27]
Hello,
I am trying to use transit-custom-posts with the Transit Base Template.
However, upon import of my GTFS feed and my timetables generated on gtfstohtml.com (both are imported via the manual import feature), I have some issues:
1) Only one route page is created, instead of the 10 that should be, and this route does not contain any information/timetables.
2) Only one timetable post is created (the post matches the route that got created), but there is no HTML in the post. It's just blank.

I'm running wordpress 5.3.2.

Please provide me with possible solutions.

Thanks ahead of time!

**Comment by thomastrillium** [comment]
Hi--apologies but we don't have the capacity at this time to address bugs from users in most circumstances at this time. Thanks for your interest but closing as we won't be able to address in a timely fashion.

**Comment by dudebrains01** [comment]
Just FYI I figured out that the issue was with the GTFS file used.
The GTFS feed in question had .txt files encoded in UTF-8 with BOM. Converting it to UTF-8 (no BOM) fixed it.

**Comment by thomastrillium** [comment]
We appreciate the follow up @dudebrains01 

opening in case @NomeQ thinks this is a bug we should fix
